services:
  connect:
    image: foo
    container_name: kafka-connect
    ports:
      - '8083:8083'
    environment:
      - "CONNECT_BOOTSTRAP_SERVERS=kafka:9092"
      - "CONNECT_REST_PORT=28082"
      - "CONNECT_GROUP_ID=kafka-connect"
      - "CONNECT_CONFIG_STORAGE_TOPIC=kafka-connect-config"
      - "CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1"
      - "CONNECT_OFFSET_STORAGE_TOPIC=kafka-connect-offset"
      - "CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1"
      - "CONNECT_OFFSET_STORAGE_PARTITIONS=-1"
      - "CONNECT_OFFSET_PARTITION_NAME=kafka-connect.1"
      - "CONNECT_STATUS_STORAGE_TOPIC=kafka-connect-status"
      - "CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1"
      - "CONNECT_STATUS_STORAGE_PARTITIONS=-1"
      - "CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter"
      - "CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false"
      - "CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter"
      - "CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://kafka-schema-registry:8081"
      - "CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false"
      - "CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter"
      - "CONNECT_INTERNAL_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter"
      - "CONNECT_PRODUCER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      - "CONNECT_CONSUMER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      - "CONNECT_REST_ADVERTISED_HOST_NAME=connect"
      - "CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/java/plugins,/usr/share/confluent-hub-components"
      - "CONNECT_LOG4J_LOGGERS=org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    healthcheck:
      test: bash -c "/bin/kafka-topics --bootstrap-server localhost:9092 --list"
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
